// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "GubJumping":return img`
..............2222..............
.............222222.............
............fffffff.............
...........222222222............
..........22222222222...........
.........f7effeeffe722..........
.........feeff77ffee7f..........
.........feeeeeeeeee7f..........
.........feeeeeeeeee7f..........
.........f7eee77eee77f..........
.........f76677776677f..........
.........f767ffff7677f..........
..........f767777677f...........
...........f7666677f............
............ff66fff.............
.......dd.....66.....dd.........
.......dd......f.....dd.........
.......ff....ffff....ff.........
.......ffffffffffffffff.........
.......ffffffffffffffff.........
..........ffffffffff............
..........ffffffffff............
..........ffffffffff............
..........ffffffffff............
..........ffff555fff............
..........2222555222............
..........8888555888............
.........888888888888...........
.........888888888888...........
........888888..888888..........
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
